name: meson

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  ubuntu-20:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        buildtype:
          - plain
          - debug
          - debugoptimized
          - release
          - minsize
        cc:
          - gcc
          - gcc-7
          - gcc-8
          - gcc-9
          - gcc-10
          - clang
          - clang-7
          - clang-8
          - clang-9
          - clang-10
    env:
      CC: ${{ matrix.cc }}
    steps:
    - uses: actions/checkout@main
    - run: sudo apt-get update
    - run: sudo apt-get install -yqq --no-install-recommends meson ninja-build ${{ matrix.cc }}
    - run: meson setup build -Dbuildtype=${{ matrix.buildtype }}
    - run: ninja -Cbuild -v

  ubuntu-22:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        buildtype:
          - plain
          - debug
          - debugoptimized
          - release
          - minsize
        cc:
          - gcc
          - gcc-9
          - gcc-10
          - gcc-11
          - gcc-12
          - clang
          - clang-11
          - clang-12
          - clang-13
          - clang-14
          - clang-15
    env:
      CC: ${{ matrix.cc }}
    steps:
    - uses: actions/checkout@main
    - run: sudo apt-get update
    - run: sudo apt-get install -yqq --no-install-recommends meson ${{ matrix.cc }}
    - run: meson setup build -Dbuildtype=${{ matrix.buildtype }}
    - run: meson compile -Cbuild -v

  debian-sid:
    runs-on: ubuntu-22.04
    container:
      image: debian:sid
    strategy:
      fail-fast: false
      matrix:
        buildtype:
          - plain
          - debug
          - debugoptimized
          - release
          - minsize
        cc:
          - gcc
          - gcc-12
          - gcc-13
          - clang
          - clang-16
          - clang-17
    env:
      CC: ${{ matrix.cc }}
    steps:
    - uses: actions/checkout@main
    - run: apt-get update && apt-get install -yqq --no-install-recommends ca-certificates gpg curl
    - run: curl -fsSL https://apt.llvm.org/llvm-snapshot.gpg.key | gpg --no-tty --dearmor -o /etc/apt/trusted.gpg.d/llvm.gpg
    - run: echo "deb http://apt.llvm.org/unstable/ llvm-toolchain-17 main" >> /etc/apt/sources.list.d/llvm.list
    - run: apt-get update && apt-get install -yqq --no-install-recommends build-essential meson ${{ matrix.cc }}
    - run: meson setup build -Dbuildtype=${{ matrix.buildtype }}
    - run: meson compile -Cbuild -v

  alpine:
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.image }}
    strategy:
      fail-fast: false
      matrix:
        image:
          - alpine:edge
          - alpine:latest
        buildtype:
          - plain
          - debug
          - debugoptimized
          - release
          - minsize
        cc:
          - gcc
          - clang
    env:
      CC: ${{ matrix.cc }}
    steps:
    - uses: actions/checkout@main
    - run: apk --no-cache add build-base meson ${{ matrix.cc }}
    - run: meson setup build -Dbuildtype=${{ matrix.buildtype }}
    - run: meson compile -Cbuild -v

  tcc:
    runs-on: ubuntu-latest
    container:
      image: alpine:edge
    strategy:
      fail-fast: false
      matrix:
        buildtype:
          - plain
          - debug
          - debugoptimized
          - release
          - minsize
    env:
      CC: tcc
    steps:
    - uses: actions/checkout@main
    - run: echo 'https://dl-cdn.alpinelinux.org/alpine/edge/testing' >> /etc/apk/repositories
    - run: apk --no-cache add build-base muon tcc samurai
    - run: muon setup -Dbuildtype=${{ matrix.buildtype }} build
    - run: samu -Cbuild -v

  analyzer:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - run: sudo apt-get update
    - run: sudo apt-get install -yqq --no-install-recommends meson
    - run: meson setup build -Dbuildtype=debug -Danalyzer=true
    - run: meson compile -Cbuild -v
